server:
  port: 8000

spring:
  data:
    mongodb:
      database: smartroads

  redis:
    host: 127.0.0.1
    port: 6379

sendgrid:
  key: ${CLEAN_CITY_SENDGRID_KEY}

cloudinary:
  name: clean-city
  key: ${CLEAN_CITY_CLOUDINARY_KEY}
  secret: ${CLEAN_CITY_CLOUDINARY_SECRET}

security:
  oauth2:
    resource:
      filter-order: 3

client:
  url: https://cleancity-web.herokuapp.com/signup/

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG

#  devtools:
#    remote:
#      secret: c21hcnQgcm9hZHMgc2VjcmV0IGtleQ==