spring:
  data:
    mongodb:
      database: smartroads
  redis:
    host: 127.0.0.1
    port: 6379

social:
  facebook:
    appId: 1715128575194570
    appSecret: f19f6e151d2c4750486b9fe3682f2101

#  profiles:
#    active: heroku

security:
  oauth2:
    resource:
      filter-order: 3

server:
  port: 8000

logging:
  level:
    org:
      springframework:
        web: DEBUG


#  devtools:
#    remote:
#      secret: c21hcnQgcm9hZHMgc2VjcmV0IGtleQ==
