server:
  port: 8000

#spring:
#  data:
#    mongodb:
#      database: smartroads
spring:
  data:
    mongodb:
      uri: mongodb://gleb:root@ds111319.mlab.com:11319/heroku_wb0cp1lr
      database: heroku_wb0cp1lr

  redis:
    host: 127.0.0.1
    port: 6379

sendgrid:
  key: ${CLEAN_CITY_SENDGRID_KEY}

cloudinary:
  name: clean-city
  key: ${CLEAN_CITY_CLOUDINARY_KEY}
  secret: ${CLEAN_CITY_CLOUDINARY_SECRET}

client:
  url: https://cleancity-web.herokuapp.com/signup

security:
  oauth2:
    resource:
      filter-order: 3

google:
  apiKey: AIzaSyAe2b0y52Ft-GElgJQR1Xo7FMIEfOpS6SI

logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      kpi:
        diploma: DEBUG

#  devtools:
#    remote:
#      secret: c21hcnQgcm9hZHMgc2VjcmV0IGtleQ==