spring:
  redis:
    url: ${CLEAN_CITY_HEROKU_REDIS_URL}

  data:
    mongodb:
      password: ${CLEAN_CITY_HEROKU_MONGO_PASSWORD}
      username: heroku_66krdg88
      database: heroku_66krdg88
      host: ds139869.mlab.com
      port: 39869