mongo:
  credentials:
    user: heroku_66krdg88
    password: ht70l8gnd3qrg0p508nhr6jodv
  address:
    host: ds139869.mlab.com
    port: 39869
  database:
    name: heroku_66krdg88

#      uri: mongodb://heroku_66krdg88:ht70l8gnd3qrg0p508nhr6jodv@ds139869.mlab.com:39869/heroku_66krdg88
